[package]
name = "day_7"
version = "0.1.0"
authors = ["Sam Kearney <samuelmkearney@gmail.com>"]
edition = "2018"

[dependencies]
intcode_computer = { version = "0.1.0", path = "../intcode_computer" }
permutohedron = "0.2.4"
